# This is a basic workflow to help you get started with Actions

name: PR label by Files

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Push Labeler
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Labeler
      uses: docker://decathlon/pull-request-labeler-action:2.0.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Here we can override the path for the action configuration. If none is provided, default one is `.github/label-pr.yml`
          CONFIG_PATH: ${{ secrets.GITHUB_WORKSPACE }}/.github/label-pr.yml
